# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-18 02:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='kerja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kerja', models.CharField(max_length=100)),
                ('exp', models.PositiveIntegerField()),
                ('gender', models.CharField(max_length=30)),
                ('sal', models.CharField(default='Classified', max_length=30)),
                ('job_type', models.CharField(max_length=30)),
                ('umur', models.CharField(max_length=30)),
                ('kota', models.CharField(max_length=100)),
                ('job_req', models.TextField(default='')),
                ('jobs_desc', models.TextField(default='')),
                ('comp_name', models.CharField(max_length=50)),
                ('comp_address', models.TextField(default='')),
                ('comp_desc', models.TextField(default='')),
                ('comp_phone', models.CharField(max_length=12)),
                ('comp_sites', models.CharField(max_length=40)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perusahaan', models.CharField(max_length=30)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
